
parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: thumbup_dev
    database_user: app_user
    database_password: 528699
    mailer_transport: mail
    mailer_host: localhost
    mailer_port: false
    mailer_user: null
    mailer_password: null
    locale: en
    secret: b343e39919e76c69e891b6c9a52bc37fa7cd209d

    facebook: 'https://graph.facebook.com'