admin_api:
    resource: "@AdminApiBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /admin/api

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

api_v1:
    resource: "@AppBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /{_locale}/api/v1
    requirements:
        _locale: ^[a-z]{2}$
    defaults: 
        _locale: en

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc