#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

api_v1:
    resource: "@AppBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api/v1

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc