#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

api_v1:
    resource: "@AppBundle/Resources/config/routing.yml"
    type:     rest
    defaults: {_format: json}
    prefix:   /api/v1
