# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments: ["@service_container"]

    api_key_authenticator:
        class: AppBundle\Security\ApiKeyAuthenticator
        arguments: ["@api_key_user_provider", "@service_container"]

imports:
    - { resource: '@AppBundle/Resources/config/services.xml' }