api_v1_test:
    prefix: /
    type: rest
    resource: "AppBundle\Controller\DefaultController"
    name_prefix: api_v1_

api_v1_login:
    prefix: /login
    type: rest
    resource: "AppBundle\Controller\\LoginController"
    name_prefix: api_v1_login_    

api_v1_logout:
    type: rest
    resource: "AppBundle\Controller\\LogoutController"
    name_prefix: api_v1_
    
api_v1_register:
    type: rest
    resource: "AppBundle\Controller\RegisterController"
    name_prefix: api_v1_    
    
api_v1_user:
    prefix: /user
    type: rest
    resource: "AppBundle\Controller\UserController"
    name_prefix: api_v1_user_

api_v1_friend:
    prefix: /friend
    type: rest
    resource: "AppBundle\Controller\FriendController"
    name_prefix: api_v1_friend_