api_v1_test:
    prefix: /example
    type: rest
    resource: "AppBundle\Controller\DefaultController"
    name_prefix: api_v1_

api_v1_login:
    prefix: /secured
    type: rest
    resource: "AppBundle\Controller\SecuredController"
    name_prefix: api_v1_    

api_v1_user:
    prefix: /user
    type: rest
    resource: "AppBundle\Controller\UserController"
    name_prefix: api_v1_
