<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
	public function getActivitiesByUser(User $user)
    {
	 	$qb = $this->_em
		            ->createQueryBuilder()
				    ->select('a')
				    ->from($this->_entityName, 'a')
				    ->join('a.user', 'u')
				    ->leftJoin('u.myFriends', 'mf', 'with', 'mf.id = :userId')
				    ->setParameter('userId', $user->getId())
					->where('a.parentId IS NULL')
				    ->groupBy('a.id')
				    ->orderBy('a.created', 'DESC')
					->getQuery()
				  ->getResult();
				//    ->getQuery()->getSQL();
			//	var_dump($qb);die;
		return $qb;

    }
}
