<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use AppBundle\Entity\User;

/**
 * CheckinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckinRepository extends EntityRepository
{
    public function getCheckinsByUser(User $user)
    {
        $qb = $this->_em
                    ->createQueryBuilder()
                    ->select('a')
                    ->from($this->_entityName, 'a')
                    ->join('a.user', 'u')
                    ->leftJoin('u.myFriends', 'mf', 'with', 'mf.id = :userId')
                    ->setParameter('userId', $user->getId())
                    ->groupBy('a.id')
                    ->orderBy('a.created', 'DESC')
                    ->getQuery()
                //    ->getQuery()->getSQL();
                    ->getResult();
        return $qb;
                //var_dump($qb);die;
    }
}