<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RideOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RideOfferRepository extends EntityRepository
{
}
