<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SocialLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialLoginRepository extends EntityRepository
{
}
