<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity as Entity;

/**
 * TripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripRepository extends EntityRepository
{

    public function getRideRequestByUser(Entity\User $user)
    {
        return $this->_em
                    ->createQueryBuilder()
                    ->select('t')
                    ->from($this->_entityName, 't')
                    ->where('t.user = :User')
                    ->andWhere('t.driver IS NULL')
                    ->setParameter('User', $user)
                    ->getQuery()
                    ->getResult();
    }
}
