<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

	public function getUserByApiKey($apiKey)
	{
		return $this->_em
		            ->createQueryBuilder()
					->select('u')
					->from($this->_entityName, 'u')
					->join('u.token', 't')
					->where('t.key = :key')
					->setParameter('key', $apiKey)
					->getQuery()
					->getOneOrNullResult();
	}
}
